import type { Metadata } from "next";
import { Sofia_Sans_Condensed, Poppins } from "next/font/google";
import "@/styles/globals.css"
import 'lenis/dist/lenis.css'
import Header from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import LenisProviders from "./lenisProviders";


export const metadata: Metadata = {
  title: "Anivio portfolio",
  description: "Generated by create next app",
};

const sofia = Sofia_Sans_Condensed({
  subsets: ["latin"],
  variable: "--font-sofia-con",
});

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppin",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${sofia.variable} ${poppins.variable}`}>
      <body>
        <LenisProviders>
          <Header />
          {children}
          <Footer />
        </LenisProviders>
      </body>
    </html>
  );
}
