import type { Metadata } from "next";
import { Sofia_Sans_Condensed } from "next/font/google";
import "@/styles/globals.css"
import 'lenis/dist/lenis.css'
import Header from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import LenisProviders from "./lenisProviders";


export const metadata: Metadata = {
  title: "Anivio portfolio",
  description: "Generated by create next app",
};

const sofia = Sofia_Sans_Condensed({
  subsets: ["latin"],
  variable: "--font-sofia-con",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={sofia.variable}>
      <body>
        <LenisProviders>
          <Header />
          {children}
          <Footer />
        </LenisProviders>
      </body>
    </html>
  );
}
